### ISSUE TITLE
feature suggestion

### ISSUE THREAD

**Issue by winsonet** [RonaldTreur/STSS#16]
Hi, thank you  for this great project! It's can save many of my time! But I have a suggestion I don't know whether can do that, can you get the alloy globals value in the stss file? for example, I set a device width to a global value like this:

`Alloy.Globals.DeviceWidth = Ti.Platform.displayCaps.platformWidth`

if I can get this in stss, I want to do some checking or calculation, like following

```
#content{
    height: 200dp;
    width: Alloy.Globals.DeviceWidth / 2;
}
```

Is this possible?

Thanks!

**Comment by RonaldTreur** [comment]
@winsonet Sorry for the (very!) late reply, but the article @rtuin's referred to seems to be the only valid approach to do this.

STSS has no knowledge about values you declared in your alloy.js. And even if it would (which will never happen) that would not be enough, since you are simply assigning another constant to your global property. One which we also don't know the value of during compilation of the STSS data.

So I'm closing this for now.

**Comment by winsonet** [comment]
I see, thanks for your reply!
